FROM golang:1.23

ARG GITHUB_TOKEN=${GITHUB_TOKEN}
ENV GITHUB_TOKEN=${GITHUB_TOKEN}

ARG GH_AUTH_TOKEN=${GH_AUTH_TOKEN}
ENV GH_AUTH_TOKEN=${GH_AUTH_TOKEN}

ARG GITHUB_OWNER=${GITHUB_OWNER}
ENV GITHUB_OWNER=${GITHUB_OWNER}

ARG GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
ENV GITHUB_REPOSITORY=${GITHUB_REPOSITORY}

ARG GITHUB_PULL_REQUEST_NUMBER=${GITHUB_PULL_REQUEST_NUMBER}
ENV GITHUB_PULL_REQUEST_NUMBER=${GITHUB_PULL_REQUEST_NUMBER}

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY *.go ./
COPY entrypoint.sh /entrypoint.sh

RUN #CGO_ENABLED=0 GOOS=linux go build -o /prwhisper
RUN go build -o /app/prwhisper

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]